export const mainDescriptions = [
  'Summary screen with the side navigation collapsed.',
  'Summary screen with the side navigation expanded and top menu visible.',
  'Events screen displaying real-time on-chain notifications.',
  'Managed accounts with active subscriptions, grouped by network.',
  'Subscription settings for account balance notifications.',
  'Subscription settings for nomination pool notifications.',
  'OpenGov overview showing networks with active subscriptions.',
  'Active OpenGov subscriptions on the Polkadot network.',
  'Send screen for initiating native token transfers.',
  'Network connection controls in the main window footer.',
];

export const viewDescriptions = [
  'Choose an import method to add your blockchain accounts.',
  'Account list view with controls to manage and monitor your accounts.',
  'Use the account dropdown to rename or show the full address, open a block explorer, and more.',
  'The manage dialog provides account management controls across all supported networks.',
  'Rename multiple accounts at once using the unified rename dialog.',
  'Import accounts via WalletConnect using a guided interface.',
  'Import accounts from a connected Ledger device through a streamlined UI.',
  'Select a target network when importing from a Ledger device.',
  'Paste any blockchain address from a supported network to import it as read-only.',
  'View, sign, and manage transactions in the dedicated Extrinsics view.',
  'Sign a transaction, remove it, or review its details using the dropdown menu.',
  'The transaction summary dialog displays detailed information for review.',
  'Submit transactions using purpose-built signing overlays.',
  'View treasury and OpenGov data, and subscribe to referenda from the OpenGov view.',
  'Browse active and historical referenda using filters and search tools.',
  'Filter the referenda list by toggling specific status options.',
  'Quickly find a referendum by searching for its ID.',
  'Customize Polkadot Live through the settings view.',
  'Back up or restore your Polkadot Live data from the settings view.',
];
