export const mainDescriptions = [
  'Summary screen displaying an overview of accounts.',
  'Summary screen displaying an overview of received events.',
  'Summary screen with the top menu open.',
  'Events screen showing categorized events with item counts.',
  'Event items listed in the balances category. ',
  'Event items listed in the nominating category. ',
  'Event data for a bonding event.',
  'Chain subscriptions screen with available networks listed.',
  'Subscription categories for the Polkadot Asset Hub network.',
  'Staking subscriptions for the Polkadot Asset Hub network.',
  'Referenda subscriptions for the Polkadot Asset Hub network.',
  'Account subscriptions screen listing imported accounts.',
  'Account subscriptions for an imported Kusama account.',
  'Account subscriptions for an imported Polkadot account.',
  'OpenGov subscriptions screen showing networks with active referenda.',
  'OpenGov subscriptions for an active referendum.',
  'Initial send screen interface.',
  'Send screen network selection dialog.',
  'Send screen with the transaction summary displayed.',
  'Expanded footer displaying connected and available networks.',
];

export const viewDescriptions = [
  'Choose an import method to add your blockchain accounts.',
  'Account list view with controls to manage and monitor your accounts.',
  'Use the account dropdown to rename or show the full address, open a block explorer, and more.',
  'The manage dialog provides account management controls across all supported networks.',
  'Rename multiple accounts at once using the unified rename dialog.',
  'Import accounts via WalletConnect using a guided interface.',
  'Select a target network when importing from a Ledger device.',
  'Import accounts from a connected Ledger device through a streamlined UI.',
  'Paste any blockchain address from a supported network to import it as read-only.',
  'View, sign, and manage transactions in the dedicated Extrinsics view.',
  'Sign a transaction, remove it, or review its details using the dropdown menu.',
  'The transaction summary dialog displays detailed information for review.',
  'Submit transactions using purpose-built signing overlays.',
  'View treasury and OpenGov data, and subscribe to referenda from the OpenGov view.',
  'Browse active and historical referenda using filters and search tools.',
  'Filter the referenda list by toggling specific status options.',
  'Quickly find a referendum by searching for its ID.',
  'Customize Polkadot Live through the settings view.',
  'Back up or restore your Polkadot Live data from the settings view.',
  'Open a view directly in the tabbed interface.',
];
