name: GitHub Pages Publish

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'

      - name: Install
        run: yarn install

      - name: Build
        working-directory: '.'
        run: yarn build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./docs/dist
    env:
      NODE_ENV: 'production'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      pages: write

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
    - name: Delete Deployments
      uses: strumwolf/delete-deployment-environment@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}
        environment: github-pages
        onlyRemoveDeployments: true

    - uses: actions/download-artifact@v5
      with:
        name: github-pages
        path: site
    - uses: actions/configure-pages@v5
    - id: deployment
      uses: actions/deploy-pages@v4
